"""Added Student model

Revision ID: 540240671408
Revises: c48799ddaf00
Create Date: 2023-08-30 21:34:26.454537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '540240671408'
down_revision = 'c48799ddaf00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
